import { DroneModelKey, DronePreset, MissionSettings } from '../types';

export const DRONE_PRESETS: Record<DroneModelKey, DronePreset> = {
  mavic3e: {
    key: 'mavic3e',
    name: 'DJI Mavic 3 Enterprise (M3E)',
    category: 'Enterprise',
    droneEnumValue: 77,
    droneSubEnumValue: 0,
    payloadEnumValue: 66,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 10,
    maxSpeed: 15,
    sensorWidthMm: 17.3,
    focalLengthMm: 12.2,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    description: 'Sensor 4/3 CMOS 20MP com Obturador Mecânico (ideal para mapeamento e fotogrametria)',
  },
  mavic3t: {
    key: 'mavic3t',
    name: 'DJI Mavic 3 Thermal (M3T)',
    category: 'Enterprise',
    droneEnumValue: 77,
    droneSubEnumValue: 0,
    payloadEnumValue: 67,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 8,
    maxSpeed: 15,
    sensorWidthMm: 6.4,
    focalLengthMm: 4.4,
    imageWidthPx: 8000,
    imageHeightPx: 6000,
    description: 'Câmera Térmica 640x512 + Sensor RGB 48MP (inspeções elétricas, segurança e salvamento)',
  },
  mavic3m: {
    key: 'mavic3m',
    name: 'DJI Mavic 3 Multispectral (M3M)',
    category: 'Enterprise',
    droneEnumValue: 77,
    droneSubEnumValue: 0,
    payloadEnumValue: 68,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 9,
    maxSpeed: 15,
    sensorWidthMm: 17.3,
    focalLengthMm: 12.2,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    description: 'Câmera Multiespectral 4x5MP + RGB 20MP (agricultura de precisão e NDVI)',
  },
  matrice350: {
    key: 'matrice350',
    name: 'DJI Matrice 350 RTK (M350 + Zenmuse P1/L1/L2)',
    category: 'Industrial',
    droneEnumValue: 89,
    droneSubEnumValue: 0,
    payloadEnumValue: 50, // Zenmuse P1
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 12,
    maxSpeed: 17,
    sensorWidthMm: 35.9,
    focalLengthMm: 35.0,
    imageWidthPx: 8192,
    imageHeightPx: 5460,
    description: 'Plataforma industrial de alta autonomia com sensor Full-Frame 45MP / LiDAR',
  },
  matrice300: {
    key: 'matrice300',
    name: 'DJI Matrice 300 RTK (M300 + Zenmuse H20/P1)',
    category: 'Industrial',
    droneEnumValue: 60,
    droneSubEnumValue: 0,
    payloadEnumValue: 50,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 11,
    maxSpeed: 17,
    sensorWidthMm: 35.9,
    focalLengthMm: 35.0,
    imageWidthPx: 8192,
    imageHeightPx: 5460,
    description: 'Plataforma industrial robusta para inspeções críticas e topografia avançada',
  },
  matrice30: {
    key: 'matrice30',
    name: 'DJI Matrice 30 / 30T (M30 Series)',
    category: 'Enterprise',
    droneEnumValue: 67,
    droneSubEnumValue: 0,
    payloadEnumValue: 52,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 10,
    maxSpeed: 16,
    sensorWidthMm: 9.6,
    focalLengthMm: 7.2,
    imageWidthPx: 8000,
    imageHeightPx: 6000,
    description: 'Série compacta resistente a intempéries IP55 com Zoom 48MP e Telêmetro Laser',
  },
  p4rtk: {
    key: 'p4rtk',
    name: 'DJI Phantom 4 RTK (P4 RTK)',
    category: 'Enterprise',
    droneEnumValue: 30,
    droneSubEnumValue: 0,
    payloadEnumValue: 20,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 8,
    maxSpeed: 13,
    sensorWidthMm: 13.2,
    focalLengthMm: 8.8,
    imageWidthPx: 5472,
    imageHeightPx: 3648,
    description: 'Drone clássico de alta precisão topográfica com obturador mecânico de 1 polegada',
  },
  mini4pro: {
    key: 'mini4pro',
    name: 'DJI Mini 4 Pro (Waypoint / Litchi / Fly)',
    category: 'Consumer / Pro',
    droneEnumValue: 99,
    droneSubEnumValue: 0,
    payloadEnumValue: 99,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 7,
    maxSpeed: 12,
    sensorWidthMm: 9.6,
    focalLengthMm: 6.7,
    imageWidthPx: 8064,
    imageHeightPx: 6048,
    description: 'Sub-249g com suporte nativo a Waypoints no DJI Fly e aplicativos de terceiros',
  },
  mini3pro: {
    key: 'mini3pro',
    name: 'DJI Mini 3 Pro (Litchi / Rainbow / CSV)',
    category: 'Consumer / Pro',
    droneEnumValue: 98,
    droneSubEnumValue: 0,
    payloadEnumValue: 98,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 7,
    maxSpeed: 12,
    sensorWidthMm: 9.6,
    focalLengthMm: 6.7,
    imageWidthPx: 8064,
    imageHeightPx: 6048,
    description: 'Compacto 48MP 4K HDR para voos programados em CSV/KML',
  },
  air3: {
    key: 'air3',
    name: 'DJI Air 3 (Waypoint / Fly / CSV)',
    category: 'Consumer / Pro',
    droneEnumValue: 95,
    droneSubEnumValue: 0,
    payloadEnumValue: 95,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 8,
    maxSpeed: 14,
    sensorWidthMm: 9.6,
    focalLengthMm: 6.7,
    imageWidthPx: 8064,
    imageHeightPx: 6048,
    description: 'Câmera dupla (24mm + 70mm) com suporte a Waypoints integrados',
  },
  custom: {
    key: 'custom',
    name: 'Drone DJI Personalizado / Outro Modelo',
    category: 'Enterprise',
    droneEnumValue: 77,
    droneSubEnumValue: 0,
    payloadEnumValue: 66,
    payloadSubEnumValue: 0,
    payloadPositionIndex: 0,
    defaultSpeed: 8,
    maxSpeed: 15,
    sensorWidthMm: 17.3,
    focalLengthMm: 12.2,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    description: 'Configuração genérica compatível com DJI Pilot 2, DJI Terra e Litchi',
  },
};

export const DEFAULT_MISSION_SETTINGS: MissionSettings = {
  missionName: 'Missao_DJI_Voo',
  dronePresetKey: 'mavic3e',
  altitudeMode: 'relativeToStartPoint',
  flightAltitude: 60, // 60 metros padrão seguro
  flightSpeed: 8, // 8 m/s (~29 km/h)
  maxFlightSpeed: 14,
  takeoffSecurityHeight: 25, // 25m de segurança
  finishAction: 'goHome',
  exitOnRCLost: 'executeLostAction',
  executeRCLostAction: 'goBack',
  headingMode: 'followWayline',
  fixedHeadingAngle: 0,
  gimbalPitch: -90, // -90 Nadir para mapeamento/ortofoto
  turnMode: 'toPointAndStopWithDiscontinuityCurvature',
  actionOnWaypoint: 'takePhoto',
  hoverSeconds: 1,

  isGridGenerated: false,
  gridAngle: 0,
  gridSpacing: 35, // 35m de faixa lateral
  frontOverlap: 75,
  sideOverlap: 65,
  margin: 0,
  photoIntervalDist: 20,
};
